// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

import 'package:kmbiame/src/models/swap_base_model.dart';
import 'package:kmbiame/src/models/user_base_model.dart';
import 'package:kmbiame/src/shared/constants/article_type.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'article_base_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'article_base_model.g.dart';

///Clase encargada de controlar los intercambios de los usuarios y dentro contiene los artículos.
@freezed
class ArticleBaseModel with _$ArticleBaseModel {
  @JsonSerializable(explicitToJson: true)
  const factory ArticleBaseModel({
    int? idArticle,
    String? name,
    String? image,
    String? description,
    bool? give,
    ArticleType? articleType,
    SwapBaseModel? swap,
  }) = _ArticleBaseModel;

  factory ArticleBaseModel.fromJson(Map<String, Object?> json) =>
      _$ArticleBaseModelFromJson(json);
}
