// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user_base_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user_base_model.g.dart';

@freezed
class UserBaseModel with _$UserBaseModel {
  @JsonSerializable(explicitToJson: true)
  const factory UserBaseModel({
    int? idUser,
    String? username,
    String? image,
    String? phone,
    String? adress,
  }) = _UserBaseModel;

  factory UserBaseModel.fromJson(Map<String, Object?> json) =>
      _$UserBaseModelFromJson(json);
}
