// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:kmbiame/src/models/article_base_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'articles_logical_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'articles_logical_model.g.dart';

///Clase encargada de controlar los artículos intercambiados por el usuario.
@freezed
class ArticlesLogicalModel with _$ArticlesLogicalModel {
  @JsonSerializable(explicitToJson: true)
  const factory ArticlesLogicalModel({
    ArticleBaseModel? give,
    ArticleBaseModel? obtain,
  }) = _ArticlesLogicalModel;

  factory ArticlesLogicalModel.fromJson(Map<String, Object?> json) =>
      _$ArticlesLogicalModelFromJson(json);
}
