// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:kmbiame/src/models/logic/articles_logical_model.dart';

import 'package:kmbiame/src/models/swap_base_model.dart';
import 'package:kmbiame/src/models/user_base_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'swap_logical_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'swap_logical_model.g.dart';

///Clase encargada de controlar los intercambios de los usuarios y dentro contiene los artículos.
@freezed
class SwapLogicalModel with _$SwapLogicalModel {
  @JsonSerializable(explicitToJson: true)
  const factory SwapLogicalModel(
      {SwapBaseModel? swap,
      ArticlesLogicalModel? articles}) = _SwapLogicalModel;

  factory SwapLogicalModel.fromJson(Map<String, Object?> json) =>
      _$SwapLogicalModelFromJson(json);
}
