// This file is "main.dart"
import 'package:kmbiame/src/models/user_base_model.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user_register_logical_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user_register_logical_model.g.dart';

///Clase encargada de controlar los artículos intercambiados por el usuario.
@freezed
class UserRegisterLogicalModel with _$UserRegisterLogicalModel {
  @JsonSerializable(explicitToJson: true)
  const factory UserRegisterLogicalModel({
    @JsonKey(name: "user") required UserBaseModel userBaseModel,
    @JsonKey(name: "accessToken") required String token,
  }) = _UserRegisterLogicalModel;

  factory UserRegisterLogicalModel.fromJson(Map<String, Object?> json) =>
      _$UserRegisterLogicalModelFromJson(json);
}
